"""Add created_at and updated_at to Employee

Revision ID: 066915a29d25
Revises: d9293cb444f7
Create Date: 2024-11-24 16:39:35.994472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066915a29d25'
down_revision = 'd9293cb444f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('ix_employees_first_name')
        batch_op.drop_index('ix_employees_last_name')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('paygrade',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('paygrade',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('ix_employees_last_name', ['last_name'], unique=False)
        batch_op.create_index('ix_employees_first_name', ['first_name'], unique=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
